server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://123.249.105.50:3306/zhilong_interview
    username: root
    password: wzlwzl
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

  redis:
    host: 123.249.105.50
    password: wzlwzl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
  path: D:\markdonw_file\