server:
  port: 8080
  ssl: #ssl配置
    enabled: true  # 默认为true
    #key-alias: alias-key # 别名(可以不进行配置)
    # 保存SSL证书的秘钥库的路径
    key-store: classpath:wldd.xyz.jks
    #key-store-password: 证书密码
    key-store-type: jks
    key-store-password: g4796q2298q8

spring:
  datasource:
    url: jdbc:mysql://123.249.105.50:3306/zhilong_interview
    username: root
    password: wzlwzl
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000   #不能小于30秒，否则默认回到1800秒
      connection-test-query: SELECT 1

  redis:
    host: 123.249.105.50
    password: wzlwzl

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

file:
#  path: D:\markdonw_file\
  path: /web_data/markdown/